version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: resilience_backend
    ports:
      - "8000:8000"
    volumes:
      - ./mapathon-490712-16e5beef6c1e.json:/app/gee_key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gee_key.json
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: resilience_frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped
